import Link from 'next/link';
import Head from 'next/head';
import Layout from '../../components/layouts';
import React, { useState, FormEvent } from 'react'; // useState for form state and response from API
import styles from '@component/styles/Home.module.css'


export default function Start() {

    const [chat, setChat] = useState<string>("");
    const [isLoading, setIsLoading] = useState<boolean>(false);
    const [response, setResponse] = useState<string>("");

    const handleChange = (e: FormEvent) => {
        const form = e.target as HTMLFormElement
        setChat(form.value);
    }

    const getResponse = async () => {
        setResponse("");
        console.log("Getting response from ChatGPT...");
        setIsLoading(true);
        const response = await fetch("/api/openai", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ message: chat }),
        });
    
        const data = await response.json();
        setIsLoading(false);
        console.log(data.text.content);
        setResponse(data.text.content);
      };

    return (
        <>
            <Head>
                <title>Chatbot</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.center}>
                    <h1 className={styles.title}>Chatbot</h1>
                </div>
                <div className={styles.center}>
                    <textarea
                        className={styles.promptInput}
                        placeholder="Say Something!"
                        onChange={handleChange}
                        rows={5}
                        cols={50}
                    />
                    </div>
                    <div className={styles.center}>
                    <button className={styles.button} onClick={getResponse}>
                        Get Response
                    </button>
                    </div>

                    <div className={styles.response}>
                        {isLoading ? (
                        <div>Waiting for response ...</div>
                        ) : (
                        <div>{response}</div>
                        )}
                    </div>

                <h3>   
                    <Link href="/">Back to home</Link>
                </h3>
            </main>
        </>
    );
}