import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@component/styles/Home.module.css'
import Link from 'next/link'

require('dotenv').config()

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Chat Bot v1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          {/* <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p> */}
        </div>

        <Link href="/chatbot/start">
          <div className={styles.center}>
            <h1 className="title">
              Welcome to the ChatBot Automation!
            </h1>
            {/* <h2>
              Click here to start
            </h2> */}
          </div>
        </Link>

      </main>
    </>
  )
}
